export const carouselData = {
  status_code: 200,
  status: "SUCCESS",
  data: [
    {
      id: "47",
      KeyIndex: "47",
      bannerId: "035e2366-dcf4-11ec-963e-064df626ed42",
      pageName: "Career",
      serialNumber: "2",
      mobileImageURL:
        "https://api.timesascent.com/recruiterpostjob/staticTimes_Ascent_Home_Banner_Mobile.webp/2022/05/26/1653570112.webp",
      desktopImageURL:
        "https://api.timesascent.com/recruiterpostjob/staticTimes_Ascent_Home_Banner.webp/2022/05/26/1653570112.webp",
      redirectionDesktopUrl: "",
      redirectionMobileUrl: "",
      isPublished: "1",
      isDeleted: "0",
      createdAt: "2022-05-26T18:31:52",
      UpdatedAt: "2022-05-26T18:31:52",
    },
    {
      id: "159",
      KeyIndex: "159",
      bannerId: "c9c2335c-8cf6-11ed-8fdc-064df626ed42",
      pageName: "Career",
      serialNumber: "2",
      mobileImageURL:
        "https://api.timesascent.com/recruiterpostjob/staticmobile.webp/2023/01/05/1672922708.webp",
      desktopImageURL:
        "https://api.timesascent.com/recruiterpostjob/staticdesktop.webp/2023/01/05/1672922709.webp",
      redirectionDesktopUrl: "https://www.iftas.in/careers/",
      redirectionMobileUrl: "https://www.iftas.in/careers/",
      isPublished: "1",
      isDeleted: "0",
      createdAt: "2023-01-05T18:15:09",
      UpdatedAt: "2023-01-05T18:15:09",
    },
    {
      id: "130",
      KeyIndex: "130",
      bannerId: "ba691568-1eda-11ed-929f-064df626ed42",
      pageName: "Career",
      serialNumber: "4",
      mobileImageURL:
        "https://api.timesascent.com/recruiterpostjob/staticTR-768x307-01/2022/08/18/1660816027.webp",
      desktopImageURL:
        "https://api.timesascent.com/recruiterpostjob/staticTR-1600x400-01/2022/08/18/1660816029.webp",
      redirectionDesktopUrl: "https://timesascent.com/top-resume",
      redirectionMobileUrl: "https://timesascent.com/top-resume",
      isPublished: "1",
      isDeleted: "0",
      createdAt: "2022-08-18T15:17:09",
      UpdatedAt: "2022-08-18T15:17:09",
    },
    {
      id: "139",
      KeyIndex: "139",
      bannerId: "d1e96350-3365-11ed-929f-064df626ed42",
      pageName: "Career",
      serialNumber: "4",
      mobileImageURL:
        "https://api.timesascent.com/recruiterpostjob/staticbanner-2/2022/09/13/1663074791.webp",
      desktopImageURL:
        "https://api.timesascent.com/recruiterpostjob/staticbanner-1/2022/09/13/1663074792.webp",
      redirectionDesktopUrl: "https://timesascent.com/PsychometricTest/9Links",
      redirectionMobileUrl: "https://timesascent.com/PsychometricTest/9Links",
      isPublished: "1",
      isDeleted: "0",
      createdAt: "2022-09-13T18:43:12",
      UpdatedAt: "2022-09-13T18:43:12",
    },
    {
      id: "50",
      KeyIndex: "50",
      bannerId: "8df954d5-dcf4-11ec-963e-064df626ed42",
      pageName: "Career",
      serialNumber: "6",
      mobileImageURL:
        "https://api.timesascent.com/recruiterpostjob/staticJobBannerMobile.webp/2022/05/26/1653570344.webp",
      desktopImageURL:
        "https://api.timesascent.com/recruiterpostjob/staticJobBanner.webp/2022/05/26/1653570345.webp",
      redirectionDesktopUrl: "https://timesascent.com/latest-jobs",
      redirectionMobileUrl: "https://timesascent.com/latest-jobs",
      isPublished: "1",
      isDeleted: "0",
      createdAt: "2022-05-26T18:35:45",
      UpdatedAt: "2022-05-26T18:35:45",
    },
  ],
  message: "Data found",
};

export const articleDataa = {
  status_code: 200,
  status: "SUCCESS",
  data: {
    Guestarticle: [
      {
        keyIndex: "157114",
        ArticleId: "157114",
        articleUrl: "https://api.timesascent.com/article",
        title: "The Driving Forces Steering the Job Market in 2023",
        shortDescription:
          "As per the research and data available year 2022 witnessed record job vacancies and acute talent shortages.",
        videoLink: "",
        isPickedByEditor: "0",
        isFeaturedArticle: "1",
        readCount: "308",
        updatedDate: "5th Jan, 2023",
        createdDate: "5th Jan, 2023",
        category: "HR Professionals",
        subCategory: "Leadership",
        base_imagePath: "https://api.timesascent.com/static",
        imagePath: "/recruiterpostjob/static/2023/01/05/1672915002.webp",
        primeThumb: "",
        thumbnail: "",
        author:
          "By Ms. Meenu Bhatia | Co-founder, VMentor.ai (A tech-enabled human intervened mentorship organization)",
        Tags: "",
      },
      {
        keyIndex: "157105",
        ArticleId: "157105",
        articleUrl: "https://api.timesascent.com/article",
        title: "Top Evolving HR Trends to Watch Out for in 2023",
        shortDescription:
          "It seemed like a ‘new era’ in the world of work owing to the pandemic. However, we are once again at that point when the cases are on the rise and uncertainties galore. But the good news is that the country at large and corporates, in particular, are prepared to battle this banking on past experiences and learnings.",
        videoLink: "",
        isPickedByEditor: "0",
        isFeaturedArticle: "0",
        readCount: "1420",
        updatedDate: "3rd Jan, 2023",
        createdDate: "3rd Jan, 2023",
        category: "HR Professionals",
        subCategory: "Leadership",
        base_imagePath: "https://api.timesascent.com/static",
        imagePath: "/recruiterpostjob/static/2023/01/03/1672748621.webp",
        primeThumb: "",
        thumbnail: "",
        author: "By Ms. Anjali Byce | CHRO, STL",
        Tags: "",
      },
      {
        keyIndex: "157072",
        ArticleId: "157072",
        articleUrl: "https://api.timesascent.com/article",
        title: "Future of Upskilling for Career Professionals",
        shortDescription:
          "Research has shown that about 2.5 quintillion bytes of data is generated every day and this figure is only going to rise. This creates a lot of uncertainty as we are not in a position to figure out what’s coming next and how it will affect our daily lives.",
        videoLink: "",
        isPickedByEditor: "0",
        isFeaturedArticle: "0",
        readCount: "1185",
        updatedDate: "29th Dec, 2022",
        createdDate: "29th Dec, 2022",
        category: "HR Professionals",
        subCategory: "Leadership",
        base_imagePath: "https://api.timesascent.com/static",
        imagePath: "/recruiterpostjob/static/2022/12/29/1672318073.jpg",
        primeThumb: "",
        thumbnail: "",
        author:
          "By Ms. Lina Ashar | Co-Founder, Korroboree International Online School",
        Tags: "",
      },
      {
        keyIndex: "157068",
        ArticleId: "157068",
        articleUrl: "https://api.timesascent.com/article",
        title: "Why Should You Join a Start-up for Better Growth?",
        shortDescription:
          "In a competitive world where multinationals have a separate niche in the industry, you may be skeptical about joining a start-up.",
        videoLink: "",
        isPickedByEditor: "0",
        isFeaturedArticle: "1",
        readCount: "1369",
        updatedDate: "28th Dec, 2022",
        createdDate: "28th Dec, 2022",
        category: "HR Professionals",
        subCategory: "Leadership",
        base_imagePath: "https://api.timesascent.com/static",
        imagePath: "/recruiterpostjob/static/2022/12/28/1672251804.webp",
        primeThumb: "",
        thumbnail: "",
        author:
          "By Mr. Anil Goyal | Managing Director & CEO, CapSavvy Consultants Pvt. Ltd.",
        Tags: "",
      },
      {
        keyIndex: "156812",
        ArticleId: "156812",
        articleUrl: "https://api.timesascent.com/article",
        title: "Career Planning in the Dynamic World",
        shortDescription:
          "As per the Work Institute’s 2022 Retention Report, more than one fifth of employees left  their jobs in 2021 owing to lack of clarity regarding career. Career development and choosing a different career path were the main reasons among them.",
        videoLink: "",
        isPickedByEditor: "0",
        isFeaturedArticle: "1",
        readCount: "1688",
        updatedDate: "18th Nov, 2022",
        createdDate: "18th Nov, 2022",
        category: "HR Professionals",
        subCategory: "Leadership",
        base_imagePath: "https://api.timesascent.com/static",
        imagePath: "/recruiterpostjob/static/2022/11/18/1668773648.webp",
        primeThumb: "",
        thumbnail: "",
        author: "By Mr. Sanjay Jha | CHRO, Mahindra First Choice Wheels",
        Tags: "",
      },
      {
        keyIndex: "156797",
        ArticleId: "156797",
        articleUrl: "https://api.timesascent.com/article",
        title: "Work from Home - A Quiet Dilemma for Working Women",
        shortDescription:
          "When ‘Quiet Quitting' and ‘Great Resignations’ are all today’s buzzwords, companies are trying hard to adjust employee policies in the changed work paradigm in the post-Covid era.",
        videoLink: "",
        isPickedByEditor: "0",
        isFeaturedArticle: "1",
        readCount: "3872",
        updatedDate: "16th Nov, 2022",
        createdDate: "15th Nov, 2022",
        category: "HR Professionals",
        subCategory: "Leadership",
        base_imagePath: "https://api.timesascent.com/static",
        imagePath: "/recruiterpostjob/static/2022/11/15/1668518056.webp",
        primeThumb: "",
        thumbnail: "",
        author:
          "By Dr. Snehal Shah (Associate Dean, Academics and Research and Professor of Organisation and Leadership) and Prof. Vineeta Dwivedi (Assistant Professor, Organisation and Leadership Studies), Bhavan’s SPJIMR",
        Tags: "",
      },
      {
        keyIndex: "156780",
        ArticleId: "156780",
        articleUrl: "https://api.timesascent.com/article",
        title:
          "Role of Social Media in Shaping Workplace Practices and Culture",
        shortDescription:
          "In the twenty-first century, society was imagined as a giant machine. People were like small cogs in this machine, playing small and standardized roles.",
        videoLink: "",
        isPickedByEditor: "0",
        isFeaturedArticle: "0",
        readCount: "333",
        updatedDate: "14th Nov, 2022",
        createdDate: "14th Nov, 2022",
        category: "HR Professionals",
        subCategory: "Leadership",
        base_imagePath: "https://api.timesascent.com/static",
        imagePath: "/recruiterpostjob/static/2022/11/14/1668431068.webp",
        primeThumb: "",
        thumbnail: "",
        author:
          "By Ms. Lina Ashar | Co-Founder, Dreamtime Learning | Founder Emeritus: Kangaroo Kids & Billabong High International Schools | Happiness Advocate | Ted X Speaker",
        Tags: "",
      },
      {
        keyIndex: "156769",
        ArticleId: "156769",
        articleUrl: "https://api.timesascent.com/article",
        title: "Accept and Improvise on Your Mistakes",
        shortDescription:
          "We all make mistakes on the job, regardless of how long we've been doing it. Working hard to avoid making errors is a sign of strength, not weakness, and developing the self-discipline and composure to deal with these problems will do wonders for your career.",
        videoLink: "",
        isPickedByEditor: "0",
        isFeaturedArticle: "0",
        readCount: "608",
        updatedDate: "11th Nov, 2022",
        createdDate: "11th Nov, 2022",
        category: "HR Professionals",
        subCategory: "Leadership",
        base_imagePath: "https://api.timesascent.com/static",
        imagePath: "/recruiterpostjob/static/2022/11/11/1668161041.webp",
        primeThumb: "",
        thumbnail: "",
        author:
          "By Dr. Neerja Birla | Mental health activist, Founder, and Chairperson, Mpower - an initiative of Aditya Birla Education Trust",
        Tags: "",
      },
      {
        keyIndex: "156482",
        ArticleId: "156482",
        articleUrl: "https://api.timesascent.com/article",
        title: "Why coaching is necessary for everyone!",
        shortDescription:
          "The fast-changing nature of skill requirements & nature of jobs in an endeavor to organize the unorganized is outrageously disproportionate to the acclimatization ability of common human beings.",
        videoLink: "",
        isPickedByEditor: "0",
        isFeaturedArticle: "1",
        readCount: "2190",
        updatedDate: "4th Nov, 2022",
        createdDate: "20th Sep, 2022",
        category: "HR Professionals",
        subCategory: "Voice of HR",
        base_imagePath: "https://api.timesascent.com/static",
        imagePath: "/recruiterpostjob/static/2022/11/04/1667556528.webp",
        primeThumb: "",
        thumbnail: "",
        author: "By Mr. Sanjay Jha | CHRO, Mahindra First Choice Wheels",
        Tags: "",
      },
      {
        keyIndex: "156702",
        ArticleId: "156702",
        articleUrl: "https://api.timesascent.com/article",
        title: "Cancer and Career",
        shortDescription:
          "In May 2017, I got my first-ever promotion. 3 months later, I was diagnosed with breast cancer at the age of 25.",
        videoLink: "",
        isPickedByEditor: "0",
        isFeaturedArticle: "0",
        readCount: "2369",
        updatedDate: "28th Oct, 2022",
        createdDate: "28th Oct, 2022",
        category: "HR Professionals",
        subCategory: "Leadership",
        base_imagePath: "https://api.timesascent.com/static",
        imagePath: "/recruiterpostjob/static/2022/10/28/1666954446.webp",
        primeThumb: "",
        thumbnail: "",
        author:
          "By Ms. Megha Agarwal | Associate Partner, Economic Laws Practice",
        Tags: "",
      },
    ],
  },
  message: "data found",
};

export const webStoriesData = {
  status_code: 200,
  status: "Success",
  data: [
    {
      ID: 84,
      KeyIndex: 84,
      WebStoriesSummaryID: "1aa7607a-8541-11ed-8fdc-064df626ed42",
      Image:
        "https://api.timesascent.com/static/Images/wecare/How Can Organizations/2022/12/26/1672075018.png",
      Title:
        "How Can Organizations Assist Employees in Creating a More Comfortable Remote Workspace",
      Description:
        "The three methods listed below can have a significant influence on an organization's remote work culture.",
      IsLive: "1",
      IsDeleted: "0",
      CreatedAt: "2022-12-26T22:46:58",
      CreatedBy: "System",
      UpdatedAt: "2022-12-26T22:47:40",
      UpdatedBy: "System",
    },
    {
      ID: 83,
      KeyIndex: 83,
      WebStoriesSummaryID: "f1b7301b-853c-11ed-8fdc-064df626ed42",
      Image:
        "https://api.timesascent.com/static/Images/wecare/9 practcial/2022/12/26/1672073231.png",
      Title:
        "9 practical, well-liked, and worthwhile methods to make money online",
      Description:
        "Young individuals start to feel that they should support their living costs during their time in college.",
      IsLive: "1",
      IsDeleted: "0",
      CreatedAt: "2022-12-26T22:17:11",
      CreatedBy: "System",
      UpdatedAt: "2022-12-26T22:17:11",
      UpdatedBy: "System",
    },
    {
      ID: 82,
      KeyIndex: 82,
      WebStoriesSummaryID: "1d3f6007-853c-11ed-8fdc-064df626ed42",
      Image:
        "https://api.timesascent.com/static/Images/wecare/Break Yourself_/2022/12/26/1672072875.png",
      Title: "Break Yourself From Your Job Monotony",
      Description:
        "Let's look at the job market's unpredictability and how it affects an individual.",
      IsLive: "1",
      IsDeleted: "0",
      CreatedAt: "2022-12-26T22:11:15",
      CreatedBy: "System",
      UpdatedAt: "2022-12-26T22:11:15",
      UpdatedBy: "System",
    },
    {
      ID: 81,
      KeyIndex: 81,
      WebStoriesSummaryID: "8e029020-84f5-11ed-8fdc-064df626ed42",
      Image:
        "https://api.timesascent.com/static/Images/wecare/Start Your Cricket Career/2022/12/26/1672042570.png",
      Title: "Start Your Cricket Career",
      Description:
        "A step-by-step guide for beginners who want to pursue their career in cricket.",
      IsLive: "1",
      IsDeleted: "0",
      CreatedAt: "2022-12-26T13:46:10",
      CreatedBy: "System",
      UpdatedAt: "2022-12-26T13:46:10",
      UpdatedBy: "System",
    },
    {
      ID: 80,
      KeyIndex: 80,
      WebStoriesSummaryID: "92a42787-84ea-11ed-8fdc-064df626ed42",
      Image:
        "https://api.timesascent.com/static/Images/wecare/Rise_through_300/2022/12/26/1672037853.webp",
      Title: "5 tips to fuel your career",
      Description:
        "Rise through the ranks! Google executive shares 5 tips to fuel your career",
      IsLive: "1",
      IsDeleted: "0",
      CreatedAt: "2022-12-26T12:27:33",
      CreatedBy: "System",
      UpdatedAt: "2022-12-26T12:27:33",
      UpdatedBy: "System",
    },
    {
      ID: 79,
      KeyIndex: 79,
      WebStoriesSummaryID: "827e7d11-84e8-11ed-8fdc-064df626ed42",
      Image:
        "https://api.timesascent.com/static/Images/wecare/Creativity_is_300/2022/12/26/1672036967.webp",
      Title: "Creativity is an Act of Defiance in Workplace",
      Description:
        "Creativity is using your imagination to develop a novel concept or product. It is an artistic pursuit in virtually all instances. However, this is not the essence of creativity.",
      IsLive: "1",
      IsDeleted: "0",
      CreatedAt: "2022-12-26T12:12:47",
      CreatedBy: "System",
      UpdatedAt: "2022-12-26T12:12:47",
      UpdatedBy: "System",
    },
    {
      ID: 77,
      KeyIndex: 77,
      WebStoriesSummaryID: "191db838-84dd-11ed-8fdc-064df626ed42",
      Image:
        "https://api.timesascent.com/static/Images/wecare/6_functional_300/2022/12/26/1672032066.webp",
      Title: "6 functional skills required to be a financial analyst",
      Description:
        "It is essential to build practical awareness and aptitude on your own.",
      IsLive: "1",
      IsDeleted: "0",
      CreatedAt: "2022-12-26T10:51:06",
      CreatedBy: "System",
      UpdatedAt: "2022-12-26T10:51:06",
      UpdatedBy: "System",
    },
    {
      ID: 76,
      KeyIndex: 76,
      WebStoriesSummaryID: "37e44cfa-84dc-11ed-8fdc-064df626ed42",
      Image:
        "https://api.timesascent.com/static/Images/wecare/10_Interview_300/2022/12/26/1672031688.webp",
      Title: "Interview Hacks That Will Land You The Job",
      Description:
        "Congratulations on bagging that interview! Now you need to convince the interviewer that you are the right person for the job.",
      IsLive: "1",
      IsDeleted: "0",
      CreatedAt: "2022-12-26T10:44:48",
      CreatedBy: "System",
      UpdatedAt: "2022-12-26T10:44:48",
      UpdatedBy: "System",
    },
    {
      ID: 75,
      KeyIndex: 75,
      WebStoriesSummaryID: "d162a627-84da-11ed-8fdc-064df626ed42",
      Image:
        "https://api.timesascent.com/static/Images/wecare/How_to_pursue_300/2022/12/26/1672031086.webp",
      Title: "How to Pursue your Passion as a Career",
      Description:
        'While most of us have heard and agree with the proverb, "find a career you love, and you will never have to work a day in your life,".',
      IsLive: "1",
      IsDeleted: "0",
      CreatedAt: "2022-12-26T10:34:46",
      CreatedBy: "System",
      UpdatedAt: "2022-12-26T10:34:46",
      UpdatedBy: "System",
    },
    {
      ID: 74,
      KeyIndex: 74,
      WebStoriesSummaryID: "e7c2e8ac-78a2-11ed-8fdc-064df626ed42",
      Image:
        "https://api.timesascent.com/static/Images/wecare/How_to_take_300/2022/12/10/1670687658.webp",
      Title: "How to take a career break",
      Description:
        "Career breaks are extended and usually unpaid stretches of time off work.",
      IsLive: "1",
      IsDeleted: "0",
      CreatedAt: "2022-12-10T21:24:18",
      CreatedBy: "System",
      UpdatedAt: "2022-12-10T21:24:18",
      UpdatedBy: "System",
    },
    {
      ID: 73,
      KeyIndex: 73,
      WebStoriesSummaryID: "6f15e8e8-78a1-11ed-8fdc-064df626ed42",
      Image:
        "https://api.timesascent.com/static/Images/wecare/Make_a_Hobby_300/2022/12/10/1670687026.webp",
      Title: "Make Your Hobby a Source of Income",
      Description:
        "Here's a checklist of questions you might want to ask yourself before turning your passion into a paycheck.",
      IsLive: "1",
      IsDeleted: "0",
      CreatedAt: "2022-12-10T21:13:46",
      CreatedBy: "System",
      UpdatedAt: "2022-12-10T21:13:46",
      UpdatedBy: "System",
    },
  ],
  TotalCount: 54,
  message: "Data found",
};

export const HrProfessionalData = {
  status_code: 200,
  status: "SUCCESS",
  data: [
    {
      id: "193",
      Hrid: "193",
      KeyIndex: "193",
      fullName: "Ms. Latha Iyer",
      designation: "Chief Human Resources Officer",
      email: "",
      mobile: "",
      currentCompany: "Zaggle",
      location: "Mumbai",
      totalExperience: "17 Years",
      yrsCurrentOrg: "5 months",
      shortDescription:
        '<p style="text-align: justify;">Latha Iyer is the CHRO of Zaggle with close to 17 years of all-rounded experience and expertise in multiple dimensions of Human Resources. She has designed and deployed several HR, OD and Change management initiatives and is adept in scaling businesses, organization design, talent management, capability building, rewards, and culture transformation.</p>\r\n<p style="text-align: justify;">Prior to joining Zaggle, Latha has held various HR leadership positions in organizations like Epigamia, Reliance Industries, Herbalife Nutrition, Nielsen, and Kantar group (WPP). Latha is a post-graduate in Human Resources from Symbiosis University and a commerce graduate from Mumbai University.</p>',
      areaOfExpertise:
        "<ul>\r\n<li>Organisation development &amp; effectiveness</li>\r\n<li>Leadership Hiring and succession planning</li>\r\n<li>HR Capability building</li>\r\n<li>Culture transformation</li>\r\n</ul>",
      workHistory:
        "<p><strong>Chief Human Resources Officer<br /></strong>Zaggle<br />Aug 2022 - Present&nbsp;</p>\r\n<p><strong>Chief People Officer<br /></strong>Epigamia<br />Mar 2022 - Aug 2022&nbsp;</p>\r\n<p><strong>Head HR - Reliance Life Sciences &amp; Digital Health<br /></strong>Reliance Industries Limited<br />May 2020 - Nov 2021</p>\r\n<p><strong>Director, HR<br /></strong>Herbalife<br />Nov 2016 - May 2020&nbsp;<br /><br /><strong>Associate Director, Human Resources<br /></strong>Nielsen<br />Jul 2014 - Oct 2016</p>\r\n<p><strong>Human Resources Director<br /></strong>IMRB International<br />Jan 2008 - Jun 2014</p>\r\n<p><strong>HR Admin Associate<br /></strong>Johnson &amp; Johnson<br />Mar 2007 - Jan 2008</p>\r\n<p><strong>HR Executive<br /></strong>TCL India<br />Dec 2005 - Mar 2007&nbsp;</p>",
      awardsAchievements:
        "<ul>\r\n<li>Winner of Young HR Leader 2019&rdquo; award by The Economic Times and TA Pai Institute of Management Institute.</li>\r\n<li>Won Best Corporate Services Professional Award for FY2015.</li>\r\n<li>Won global award for &ldquo;Innovation&rdquo; under company culture category in 2019.</li>\r\n<li>Certified as for &ldquo;National HRD Excellence&rdquo; Assessor by CII (Confederation of Indian Industry).</li>\r\n</ul>",
      connectToLinkdin: "",
      connectToTwitter: "",
      website: "",
      profilePicture:
        "https://api.timesascent.com/media/HRprofessional/Ms. Latha Iyer/2022/12/22/1671689732.webp",
      currentCompanyLogo: "",
      featuredMedia: "",
      createdDate: "2022-12-22T11:45:32",
      updatedDate: "2022-12-27T14:27:13",
      isPublished: "1",
      publishDate: "",
      position: "",
      category: "",
      startdate: "",
      enddate: "",
    },
    {
      id: "182",
      Hrid: "182",
      KeyIndex: "182",
      fullName: "Mr. Rajeev Bharadwaj",
      designation: "Chief Human Resources Officer",
      email: "",
      mobile: "",
      currentCompany: "Sun Life Financial",
      location: "Gurugram",
      totalExperience: "30+ Years",
      yrsCurrentOrg: "8+ Years",
      shortDescription:
        '<p style="text-align: justify;">Mr. Bharadwaj has been a People&rsquo;s Leader with over two decades of cross-industry experience in Human Resources. Over the course of his career, he has curated and nurtured collaborative partnerships across multiple businesses and stakeholders. Functionally, over the years, he also has led and managed diverse aspects of Human Resources.</p>\r\n<p style="text-align: justify;">He is a huge believer in the role technology, culture, values, and purpose play in creating an eco-system that delivers unique and high-quality employee experiences.</p>',
      areaOfExpertise: "",
      workHistory:
        "<p>2014 &ndash; Present<br />Chief Human Resources<br />Sun Life Financial</p>\r\n<p>2008 - 2013<br />Country Head - HR &amp; Employee Services<br />LexisNexis</p>\r\n<p>2005 - 2008<br />Director HR<br />Fidelity Investments</p>\r\n<p>2002 - 2004<br />Assistant Manager&nbsp;<br />APJ Surrendra Group</p>\r\n<p>2003 - 2005<br />Corporate HR Manager<br />Baxter International Inc.</p>\r\n<p>2000 - 2003<br />HR Business Partner<br />Monster.com India</p>\r\n<p>1998 - 2000<br />Area HR Manager<br />Coca- Cola India</p>",
      awardsAchievements: "",
      connectToLinkdin: "",
      connectToTwitter: "https://twitter.com/RajeevB_SunLife",
      website: "",
      profilePicture:
        "https://api.timesascent.com/media/HRprofessional/Mr. Rajeev Bharadwaj/2022/06/23/1655984731.webp",
      currentCompanyLogo: "",
      featuredMedia:
        '<p><a href="https://www.peoplemattersglobal.com/article/culture/shine-together-make-life-brighter-and-shape-the-future-rajeev-bhardwaj-chro-sun-life-33850?fbclid=IwAR2CsVWjJKil1XRIWUSYC5HXFI0-On-Nw7iWuYOYWIdul5T3jZApreF3kTU" target="_blank" rel="noopener">Shine together, Make life brighter, and shape the future | People Matters</a></p>\r\n<p><a href="https://anz.peoplemattersglobal.com/" target="_blank" rel="noopener">Top trends in HR tech which will be relevant in near future | People Matters</a></p>\r\n<p><a href="https://hrsea.economictimes.indiatimes.com/news/talent-management/retaining-nurturing-women-talent-heres-how/91759534?fbclid=IwAR1-J1DlSxuV5Lx4wkv3SQ_AwEE4vMAU7nAYyJlDq6W4i2ERn1VGR2lX9rs" target="_blank" rel="noopener">Retaining &amp; nurturing women talent: Here\'s how? | Economic Times</a></p>',
      createdDate: "2022-06-23T17:15:31",
      updatedDate: "2022-12-27T12:47:59",
      isPublished: "1",
      publishDate: "",
      position: "5",
      category: "",
      startdate: "",
      enddate: "",
    },
    {
      id: "192",
      Hrid: "192",
      KeyIndex: "192",
      fullName: "Sanjay Kumar Jha",
      designation: "CHRO & Sr VP BD& OEM Relations",
      email: "",
      mobile: "",
      currentCompany: "Mahindra First Choice Wheels Ltd",
      location: "India",
      totalExperience: "",
      yrsCurrentOrg: "",
      shortDescription:
        '<p style="text-align: justify;">I am currently CHRO &amp; Sr VP- BD &amp; OEM Relations at Mahindra First Choice Wheels Ltd, an auto-tech Company in used vehicle ecosystem.<br /><br />I have worked in Iron &amp; Steel industry, Telecom industry, Chemical industry, and automobile industry.&nbsp; Prior to joining Mahindra Group in 2010, I served four Tata companies, as Corporate Quality Head.<br /><br />I have 30+ years of work experience in the field of operations, TQM/TPM, HR and sales in metallurgical, chemical, telecom and automobile industries. I have significantly contributed to three different organizational transformations in my capacity as Corporate Quality Head and CHRO.&nbsp; I led an organizational transformational movement, named as Jagran (awakening), where I used tools &amp; techniques like, Appreciative Inquiry, DVF&gt;R model, 7QC tools&amp; QC story, loss cost analysis, 7 -pillars of TPM and DMAIC approach. In current organization, besides many HR best practices I have implemented &ldquo;Talent 2 Value&rdquo; model of McKinsey.<br /><br />I am a certified Six Sigma Black Belt, certified ICF coach and certified FIRO-B user. I have been trained by Michigan Ross &amp;MLU in the areas of general management and by McKinsey in the areas of HR.<br /><br />My HR articles have been published in &ldquo;People Matters&rdquo; and &ldquo;Economic Times&rdquo;.<br /><br />I am a marathoner. I love reading books and watching videos primarily on the topics of latest technologies, HR, &amp; history. I follow writers and influencers like Yuval Harari, Sadhguru Jaggi and Deepak Ch0pra and Sangeet Paul Choudary.</p>',
      areaOfExpertise:
        "<p>Talent Management<br />Competency Based Interviewing<br />Process Improvement<br />Management<br />Total Productive Maintenance</p>",
      workHistory:
        "<p>CHRO &amp; Sr VP BD&amp; OEM Relations<br />Mahindra First Choice Wheels Ltd<br />Feb 2011 - Present</p>\r\n<p>Corporate Quality Head (CQH)<br />Nelco (Electronics) &amp; Tatanet (Telecom)<br />2008 - 2010</p>\r\n<p>Corporate Quality Head (CQH)<br />Rallis India Ltd (Agrochem company)<br />2003 - 2008</p>\r\n<p>Corporate Quality Head (CQH)<br />AirTel (Telecom company)<br />2002 - 2003</p>\r\n<p>Corporate Quality Head (CQH)<br />TATA METALIKS (Iron making company)<br />1995 - 2002</p>\r\n<p>Cast Iron &amp; Ferro alloy making companies<br />1989 -1995</p>",
      awardsAchievements:
        '<p>"Topmost HR Leader" (WHRDC); GPMD (Michigan Ross); PCC Level Coach (ICF); 6-Sigma Black Belt.</p>\r\n<p>&nbsp;</p>',
      connectToLinkdin: "",
      connectToTwitter: "",
      website: "",
      profilePicture:
        "https://api.timesascent.com/media/HRprofessional/Sanjay Kumar Jha/2022/11/25/1669380908.webp",
      currentCompanyLogo: "",
      featuredMedia: "",
      createdDate: "2022-11-25T18:25:08",
      updatedDate: "2022-11-25T18:25:08",
      isPublished: "1",
      publishDate: "",
      position: "",
      category: "",
      startdate: "",
      enddate: "",
    },
    {
      id: "191",
      Hrid: "191",
      KeyIndex: "191",
      fullName: "Ms. Indrani Banerjee",
      designation: "CHRO Practice Head",
      email: "",
      mobile: "",
      currentCompany: "EaseMyHR",
      location: "Kolkata",
      totalExperience: "28 years",
      yrsCurrentOrg: "10 months",
      shortDescription:
        '<p style="text-align: justify;">Seasoned HR expert with 25 years enriched and diverse specialist experience across all HR domains in corporate office &amp; shop-floors across sectors like IT, Manufacturing, Engineering, Automobile, Consulting etc. managing multi-locational work-force in large organizations.</p>\r\n<p style="text-align: justify;">Built high-performance, high-energy, well-bonded teams through exemplary leadership &amp; coaching skills (ensuring impact lasts beyond my tenure in the organization).</p>\r\n<p style="text-align: justify;">Worked closely with Big 4 Consulting firms and BCG in driving change management and organization transformation initiatives through collaboration with stakeholders at various levels.</p>\r\n<p style="text-align: justify;">All career movements were in quest of excellence, constantly seeking fresh challenges and learning opportunities once the ongoing assignment was running in &lsquo;auto-pilot&rsquo; mode; ideally suited for long-term engagement with thriving organizations.</p>',
      areaOfExpertise:
        "<p><strong>HR Strategy &amp; Roadmap</strong>: Designed and developed the overall HR strategy and implementation roadmap in alignment with business plan and people&rsquo;s aspirations; developed policies &amp; standard operating procedures to support the organization in meeting its people objectives.</p>\r\n<p><strong>Talent Acquisition &amp; On-boarding</strong>: Developed policies &amp; streamlined operating procedures to attract, select and retain the talent segment targeted by the organization. Sourced profiles (IT &amp; non-IT) spanning diverse industry segments across all levels of hierarchy including local hiring for overseas positions and expatriate hiring.</p>\r\n<p><strong>Performance Management</strong>: Created performance management framework for organization after defining key result areas and key performance indicators (aligned with business plans) for all Roles within an organization; administering the framework in an online platform on a quarterly basis, linked with quarterly variable pay pay-outs. Identified critical talent (high performance high potentials) and developed customised interventions to keep them engaged and performing at their optimum capacity.</p>\r\n<p><strong>Learning &amp; Development</strong>: Conceptualised and implemented the organization&rsquo;s capability building agenda through need analysis and creation of training execution plans; collaborated with Big 4 Consulting Firm (PwC) in deploying senior leadership development interventions (Development Center &amp; Individual Development Plan). Assessed identified leadership pipeline through an Assessment Center (Advisory Role). Developed content and delivered customised training programs based on organization need.</p>\r\n<p><strong>Compensation &amp; Benefits</strong>: Identified key roles within organization, benchmarking them for external parity (Hewitt) to design market-driven compensation; subsequently carried out internal parity exercise for similar role clusters, for identification and corrective intervention for outliers, to drive equitable and performance-driven compensation across the organization.</p>\r\n<p><strong>Employee Engagement</strong>: Administered Engagement Survey (Gallup), analysed findings and actionised on identified gaps through OD interventions.</p>\r\n<p><strong>Employee Relations</strong>: Built trust through strong human connections across the spectrum (white collar and blue collar employees) which have contributed to the creation and preservation of harmonious working relations, under challenging business circumstances.</p>\r\n<p><strong>Change Management &amp; HR Transformation</strong>: Collaborated with Big 4 Consulting Firm (PwC) in driving change management in the organization, starting with the HR function in terms of HR service delivery and HR function effectiveness.</p>\r\n<p><strong>HR Analytics</strong>: Tracked all aspects of HR functioning through HR metrices (as mandated by different quality models like PCMM, Malcolm Baldrige), for continuous improvement, process optimization and improving operational efficiency. Leveraged people data for purposeful analysis, to support better strategic decisions.</p>\r\n<p><strong>Labour Laws</strong>: Strong understanding of labour laws and their applications with respect to on-going Compliance and in resolving work related issues.</p>\r\n<p>&nbsp;</p>\r\n<p>&nbsp;</p>",
      workHistory:
        "<p>Jan 2022 &ndash; Present<br />CHRO Practice Head<br />EaseMyHR</p>\r\n<p>Nov 2017 - Present<br />Managing Partner<br />IB Consultants &amp; Co.</p>\r\n<p>Oct 2019 - Jan 2021<br />Project Director<br />Maxcellence Global Advisory &amp; Consulting</p>\r\n<p>Apr 2017 - Aug 2017<br />Chief - HR (Group CHRO)<br />A diversified business conglomerate - Group Manjushree (BK Birla)</p>\r\n<p>Sep 2015 - Apr 2017<br />Head HR<br />McNally Bharat Engineering Company limited</p>\r\n<p>2012 - Aug 2015<br />Human Resources Management Consultant<br />Independent</p>\r\n<p>2009 &ndash; 2011<br />HR Head, handling a pan-India employee base<br />McNally Bharat Engineering Company limited</p>\r\n<p>2008 - 2009&nbsp;<br />HR Business Partner, SBU Head across multiple geographies in India and abroad<br />Infosys</p>\r\n<p>2006 &ndash; 2008<br />HR Head for a global workforce<br />RS Software</p>\r\n<p>2003 &ndash; 2005<br />HR Head of the Regional Office<br />NIIT Technologies Limited</p>\r\n<p>2000 &ndash; 2003<br />HR Head of the Organization<br />Globsyn Technologies</p>\r\n<p>1998 - 2000&nbsp;<br />Member of the Regional HR team<br />DSQ Software Ltd.</p>\r\n<p>1995 &ndash; 1997<br />Member of the Personnel Department<br />Hindustan Motors Ltd.</p>",
      awardsAchievements: "",
      connectToLinkdin: "",
      connectToTwitter: "",
      website: "",
      profilePicture:
        "https://api.timesascent.com/media/HRprofessional/Ms. Indrani Banerjee/2022/11/09/1668000335.webp",
      currentCompanyLogo: "",
      featuredMedia: "",
      createdDate: "2022-11-09T17:35:10",
      updatedDate: "2022-11-14T13:39:25",
      isPublished: "1",
      publishDate: "",
      position: "2",
      category: "",
      startdate: "",
      enddate: "",
    },
    {
      id: "190",
      Hrid: "190",
      KeyIndex: "190",
      fullName: "George Varghese M",
      designation: "Chief Human Resources Officer",
      email: "",
      mobile: "",
      currentCompany: "Shahi Exports Private Limited",
      location: "Bengaluru",
      totalExperience: "21 years",
      yrsCurrentOrg: "4 months",
      shortDescription:
        '<p style="text-align: justify;">A versatile human resources professional, with 20 years of experience across Entrepreneurship, Manufacturing, IT/ ITES, Retail, and Pharma Industry. Currently engaged in a HR transformation exercise with the largest apparel manufacturing company in India.<br /><br /></p>\r\n<p style="text-align: justify;">Exhibits proven skills in HR Strategy, Organisation Design, Manpower planning, Talent Acquisition, Total Rewards, Talent Management, HR Technology and Employee Experience. Leading team of HR professionals since last 12 yrs. Astute business partner, believes and drives top-line and bottom-line focused HR Initiatives.&nbsp;</p>',
      areaOfExpertise:
        "<ul>\r\n<li>Compensation &amp; Benefits.</li>\r\n<li>Talent Acquisition.</li>\r\n<li>Performance Management.</li>\r\n<li>Organisational Effectiveness.</li>\r\n<li>HR Business Partner.</li>\r\n<li>HR Technology.</li>\r\n<li>Executive Coach to Mid-Level Management professionals in Retail, Manufacturing, ITES and Pharma sector.</li>\r\n</ul>",
      workHistory:
        "<p>Jul 22 till date<br />Chief Human Resources Officer<br />SHAHI EXPORTS PVT LTD, Bengaluru.</p>\r\n<p>Oct 20 till Jun 22<br />Head of HR &ndash; GBS<br />FAB GLOBAL BUSINESS SERVICES PVT LTD, Bengaluru.</p>\r\n<p>Jul 2019 to date<br />Director (Entrepreneur)<br />JUGEN HOSPITALITY SERVICES PVT LTD, Kerala.</p>\r\n<p>Nov 16 &ndash; Feb 19<br />Vice President &ndash; Human Resources (Group)<br />HIMATSINGKA SEIDE LIMITED, Bangalore.</p>\r\n<p>Oct 14 &ndash; Nov 16<br />Head of HR &amp; Administration &ndash; North India<br />TITAN COMPANY (TATA ENTERPRISE), Delhi.</p>\r\n<p>May 13 &ndash; Oct 14<br />HR Head &ndash; India<br />JUMBO ELECTRONICS, Noida.</p>\r\n<p>Sep 07 &ndash; Dec 12<br />Performance Management Specialist/ Manager &ndash; Total Rewards/ HR Manager &ndash; Retail/ Manager &ndash; Special Projects<br />ALGHANIM INDUSTRIES, Kuwait.</p>\r\n<p>Mar 06 &ndash; Aug 07<br />Capabilities Lead (Specialist Grade)<br />ACCENTURE SERVICES, Bangalore.</p>\r\n<p>Feb 05 &ndash; Mar 06<br />Assistant Manager<br />DR REDDY&rsquo;S LABORATORIES, Hyderabad.</p>\r\n<p>Apr 03 &ndash; Feb 05<br />Executive<br />FLEXTRONICS INDIA, Bangalore.</p>\r\n<p>Jul 02 &ndash; Feb 03<br />Management Trainee<br />GATI LIMITED, Indore/Kolkata.</p>\r\n<p><strong>&nbsp;</strong></p>\r\n<p>&nbsp;</p>",
      awardsAchievements:
        "<ul>\r\n<li>Recognized for exemplary efforts and awarded Best HOD in North region FY 15 by Titan Company (Tata Enterprise), Delhi.</li>\r\n<li>Rewards Certified on Hay&rsquo;s Framework by Robert Mosley.</li>\r\n<li>Six Sigma Green Belt.</li>\r\n<li>SHL QPQ32 certified.</li>\r\n<li>Thomas International PPA certified.</li>\r\n<li>Deloitte Performance Consultant certified.</li>\r\n<li>Managing BPO by IIM, Bangalore.</li>\r\n</ul>",
      connectToLinkdin: "",
      connectToTwitter: "",
      website: "",
      profilePicture:
        "https://api.timesascent.com/media/HRprofessional/George Varghese M/2022/11/01/1667299774.webp",
      currentCompanyLogo: "",
      featuredMedia: "",
      createdDate: "2022-11-01T16:19:34",
      updatedDate: "2022-11-04T17:13:37",
      isPublished: "1",
      publishDate: "",
      position: "1",
      category: "",
      startdate: "",
      enddate: "",
    },
    {
      id: "181",
      Hrid: "181",
      KeyIndex: "181",
      fullName: "Mr. Dhirendra Nath",
      designation: "Group Chief People Officer",
      email: "",
      mobile: "",
      currentCompany: "SLK Group",
      location: "Bangalore",
      totalExperience: "20+ Years",
      yrsCurrentOrg: "4 Years",
      shortDescription:
        '<p style="text-align: justify;">As the Group Chief People Officer at SLK Group, Dhirendra Nath (Dhiren) has led the people strategy in the midst of rapid growth in the company and chartered to make SLK, an employer of choice. A change catalyst who has been a key contributor to the transformative journey of SLK Group, from one company to a bouquet of four companies, driving synergistic capabilities across the tech spectrum. Juggling between building strong leadership and CEO transitions, building an inclusive and sustainable culture, re-engineering the people processes, and tech-enabling it by the digitization of the landscape of HR, Dhiren has closely partnered with business leaders in building an organization that is growth ready. <br />Dhiren&rsquo;s career has traversed the length and breadth of corporate HR across different countries, and during the course of his remarkable two-decade journey, has set up and scaled operations in different countries, run large, diversified businesses, and restructured and transformed existing businesses.</p>\r\n<p style="text-align: justify;">With such diverse experience, what drives Dhiren is his relentless pursuit of cracking the code on how to keep employees motivated, hale and hearty at the workplace and enable the organization to scale new peaks of success. He is a regular contributor to various forums and enjoys the opportunity to interact with students on various HR and industry topics.</p>',
      areaOfExpertise:
        '<ul>\r\n<li>&nbsp;Nurturing and Building Leadership Pipeline</li>\r\n<li style="text-align: justify;">Deep Understanding of People\'s Landscape &amp; Practices across geographies</li>\r\n</ul>',
      workHistory:
        "<p>2017 &ndash; Present<br />Group CHRO<br />SLK Group</p>\r\n<p>2006 - 2017<br />General Manager &amp; HR Head Product Engineering<br />Wipro</p>\r\n<p>2004 - 2006<br />Deputy Manager HR<br />Dr. Reddy's</p>\r\n<p>2002 - 2004<br />Assistant Manager&nbsp;<br />APJ Surrendra Group</p>\r\n<p>2001 - 2002<br />Senior Executive HR<br />Pantaloon Retail India Pvt. Ltd.</p>",
      awardsAchievements: "",
      connectToLinkdin: "",
      connectToTwitter: "",
      website: "",
      profilePicture:
        "https://api.timesascent.com/media/HRprofessional/Mr. Dhirendra Nath/2022/06/23/1655971000.webp",
      currentCompanyLogo: "",
      featuredMedia:
        '<p><a href="https://www.linkedin.com/pulse/six-feet-apart-dhirendra-nath/" target="_blank" rel="noopener">Six Feet Apart</a></p>\r\n<p><a href="https://www.linkedin.com/pulse/popping-bubble-dhirendra-nath/" target="_blank" rel="noopener">Popping the Bubble</a></p>',
      createdDate: "2022-06-23T13:26:41",
      updatedDate: "2022-11-04T17:12:50",
      isPublished: "1",
      publishDate: "",
      position: "10",
      category: "",
      startdate: "",
      enddate: "",
    },
    {
      id: "177",
      Hrid: "177",
      KeyIndex: "177",
      fullName: "Mr. Apurv Choubey",
      designation: "Chief Human Resource Officer",
      email: "",
      mobile: "",
      currentCompany: "Bridgestone India",
      location: "Pune",
      totalExperience: "27+ Years",
      yrsCurrentOrg: "3+ Years",
      shortDescription:
        "<p>A seasoned HR leader with 30 years of diverse experience in Organization Development &amp; Effectiveness, Talent Management &amp; acquisition, Compensation &amp; Benefits, HR Operations, Employee Relations, Change Management, Leadership Development, and mergers &amp; acquisitions.</p>\r\n<p>His experience spans industry verticals like Automotive, Metal, Packaging, Process Solutions &amp;Technology, and Agri input Industry.&nbsp;</p>\r\n<p>A thought leader and an HR professional with an ability to impact organizations positively with his ability to think innovatively &amp; out of the box, and this has won him many accolades.&nbsp; Widely traveled and worked on assignments in various locations across Europe, the US, and the Asia Pacific. Having worked on a special assignment on Management and Learning systems, he brings an excellent understanding of world-class HR systems and processes with a proven ability to implement and maintain them.</p>\r\n<p>Apurv has held leadership positions and has been a board member in some world-class organizations like Alcan, Tetra Pak, Honeywell, TACO, and Syngenta. His last position was with Syngenta as South Asia head of HR before he joined Bridgestone</p>\r\n<p>Apurv holds a Bachelor&rsquo;s degree in Management from BSS, Bhopal, and MBA from SIBM, Pune. Specializing in HR, he is also a PDI-certified coach.</p>",
      areaOfExpertise:
        "<ul>\r\n<li>Organization development &amp; effectiveness</li>\r\n<li>HR operations</li>\r\n<li>Talent management</li>\r\n</ul>",
      workHistory:
        "<p>2019 &ndash; Present<br />Cheif Human Resource Officer<br />Bridgestone India Pvt. Ltd.&nbsp;</p>\r\n<p>2011 - 2016<br />Country Head HR India and South Asia<br />Syngenta</p>\r\n<p>2004-2011<br />Director - Human Resources<br />Honeywell</p>\r\n<p>2002 - 2004<br />Human Resources and OD Head<br />TATA AutoComp Systems Ltd</p>\r\n<p>1999 - 2002<br />Head - Human Resources<br />Tyco Electronics</p>\r\n<p>1998 - 1999<br />HR Manager&nbsp;<br />Tetra Pak</p>\r\n<p>1991 - 1998<br />Manager - Human Resources<br />Alcan</p>",
      awardsAchievements: "",
      connectToLinkdin: "",
      connectToTwitter: "",
      website: "",
      profilePicture:
        "https://api.timesascent.com/media/HRprofessional/Mr. Apurv Choubey/2022/06/20/1655712666.webp",
      currentCompanyLogo: "",
      featuredMedia:
        '<p><a href="https://hr.economictimes.indiatimes.com/news/industry/our-long-term-strategy-is-focused-on-creating-inclusive-work-culture-apurv-choubey-chro-bridgestone-india/80181938" target="_blank" rel="noopener">Our long-term strategy is focused on creating inclusive work culture: Apurv Choubey, , CHRO, Bridgestone India</a><br /><br /><a href="https://www.financialexpress.com/express-mobility/components/bridgestone-india-inaugurates-institute-for-mobility-solutions/2490337/" target="_blank" rel="noopener">Bridgestone India Inaugurates Institute For Mobility Solutions</a><br /><br /><a href="https://auto.economictimes.indiatimes.com/news/tyres/bridgestone-takes-steps-for-psychological-wellbeing-of-employees/82774948" target="_blank" rel="noopener">Bridgestone India employee initiative: Bridgestone takes steps for psychological wellbeing of employees, Auto News, ET Auto (indiatimes.com)</a></p>',
      createdDate: "2022-06-20T13:41:06",
      updatedDate: "2022-11-04T17:12:05",
      isPublished: "1",
      publishDate: "",
      position: "20",
      category: "",
      startdate: "",
      enddate: "",
    },
    {
      id: "172",
      Hrid: "172",
      KeyIndex: "172",
      fullName: "Mr. Kumar Venkatraman",
      designation: "CHRO",
      email: "",
      mobile: "",
      currentCompany: "Gallagher Service Center (GSC)",
      location: "Bengaluru",
      totalExperience: "25+ Years",
      yrsCurrentOrg: "4 Months",
      shortDescription:
        '<p style="text-align: justify;">Mr. Kumar Venkatraman is a Global HR professional with over 25 years of core HR experience and has been associated with various industries like Manufacturing, IT, ITES &amp; Services during his tenure in this field. His strength lies in managing the human capital in Startups and HR Transformation in Organizations which are going through a cultural change. The expertise which he has picked up from large &amp; established organizations has helped him further to be robust on the corporate turf.&nbsp;</p>',
      areaOfExpertise:
        '<p style="text-align: justify;">Mr. Kumar&rsquo;s areas of expertise lie in the talent management along with a lot of experience into domains like Human resources and its policies, Vendor and Performance Management. Having an overall professional experience of more than 25 years in high profiles, Mr. Kumar have had hands on expertise into Recruitment, Leadership and Employee Engagement.</p>',
      workHistory:
        '<p style="text-align: justify;">Mr. Kumar Venkatraman is currently working with Gallagher Service Center (GSC) as a CHRO since Jan 2022 prior to which he had served esteemedorganizations like DAMAC Properties, First Advantage, Hewett Packard and prior to that he has worked for Genpact as well. Back in the year 1993, Mr. Kumar had started his journey with Rane Group. Since then he has had wide expertise into different roles into the HR Domain.</p>',
      awardsAchievements:
        '<p style="text-align: justify;">Mr. Venkatraman was awarded the 100 Top HR Minds(India) by CHRO Asia and World HR Congress in the year 2018 and as the Most Influential HR Leaders in India back in Feb 2017.</p>\r\n<p style="text-align: justify;">Apart from these, he has also been awarded as the CHRO Asia &ndash; 100 Most Influential Global HR Professional by CHRO Asia and World HR Congress in Feb 2016.</p>',
      connectToLinkdin: "",
      connectToTwitter: "",
      website: "",
      profilePicture:
        "https://api.timesascent.com/media/HRprofessional/Mr. Kumar Venkatraman/2022/04/19/1650350724.jpg",
      currentCompanyLogo: "",
      featuredMedia:
        '<p><a href="https://hr.economictimes.indiatimes.com/news/industry/gallagher-service-center-appoints-kumar-venkatraman-as-chro/90195474" target="_blank" rel="noopener">Gallagher Service Center appoints Kumar Venkatraman as CHRO</a></p>\r\n<p><a href="https://www.hrkatha.com/people/movement/kumar-venkatraman-appointed-chro-at-gallagher-service-centre/" target="_blank" rel="noopener">Kumar Venkatraman appointed CHRO at Gallagher Service Centre</a></p>\r\n<p><a href="https://sightsinplus.com/news/chro-move/gallagher-service-center-appoints-kumar-venkatraman-as-chro/" target="_blank" rel="noopener">Gallagher Service Center appoints Kumar Venkatraman as CHRO</a></p>\r\n<div>&nbsp;</div>',
      createdDate: "2022-04-19T12:15:24",
      updatedDate: "2022-11-04T17:11:45",
      isPublished: "1",
      publishDate: "",
      position: "25",
      category: "",
      startdate: "",
      enddate: "",
    },
    {
      id: "168",
      Hrid: "168",
      KeyIndex: "168",
      fullName: "Mr. Rohit Hasteer",
      designation: "Group CHRO",
      email: "",
      mobile: "",
      currentCompany: "REA India (Housing, PropTiger, Makaan)",
      location: "Gurgaon",
      totalExperience: "24+ Years",
      yrsCurrentOrg: "6 Years",
      shortDescription:
        '<p style="text-align: justify;">A thorough HR professional, who thrives on building and creating Great Places to Work and an HR setup that not only creates a conducive work culture but also builds a workforce that drives the company\'s vision. Rich experience in finding and building talent, setting up robust policies &amp; processes, honing talent through learning &amp; development, and talent management, all this while building a results-oriented and metric-driven HR team.</p>',
      areaOfExpertise:
        "<ul>\r\n<li>Talent Management</li>\r\n<li>Talent Acquisition</li>\r\n<li>Organizational Development</li>\r\n</ul>",
      workHistory:
        "<p><strong>Group CHRO</strong><br />2015 - till date<br />REA India(Housing, PropTiger, Makaan)</p>\r\n<p><strong>Director - People Management &amp; Human Resources - Indian Subcontinent</strong><br />2012 - 2015<br />UTi Worldwide Inc</p>\r\n<p><strong>Head - HR &amp; Training</strong><br />2007 - 2012<br />MakeMyTrip.com</p>\r\n<p><strong>Senior Manager - HR</strong><br />2005 - 2006<br />Aviva India Insurance Company Ltd.</p>\r\n<p><strong>AVP - HR</strong><br />2003 - 2005<br />Citifinancial Consumer Finance India Ltd.</p>",
      awardsAchievements:
        '<ul style="list-style-type: circle;">\r\n<li>REA India ranked 13th among India&rsquo;s Best Companies to Work For 2021 list and 48th in &lsquo;Best Workplaces in Asia 2021 list&rsquo; by the Great Place to Work&reg; Institute. REA India was ranked 34th in 2019 and 95th in &lsquo;India&rsquo;s Best Companies to Work For&rsquo; list. REA India also recognized amongst Top 50 Best Workplace for Women in 2021 and Top 75 Best Workplace for Women in 2017 by Great Place to Work&reg; &nbsp;</li>\r\n<li>UTi Worldwide India ranked 44th among India&rsquo;s Best Companies to Work For in 2014. UTi Worldwide India also &nbsp;won the award for the Best HR Strategy in Line with Business in the 4th Asia&rsquo;s Best Employer Brand Awards 2013</li>\r\n<li>Make My Trip ranked amongst the Top 5 companies in &lsquo;India&rsquo;s Best Companies to Work For&rsquo; list for 3 years (2010, 2011, 2012) in a row among India&rsquo;s Best Companies To Work For 2010 list by Great Place to Work&reg; Institute</li>\r\n</ul>',
      connectToLinkdin: "",
      connectToTwitter: "",
      website: "",
      profilePicture:
        "https://api.timesascent.com/media/HRprofessional/Mr. Rohit Hasteer/2022/02/07/1644234122.jpg",
      currentCompanyLogo: "",
      featuredMedia:
        '<p><a href="https://www.peoplematters.in/author/rohit-hasteer" target="_blank" rel="noopener">People Matters</a></p>\r\n<p><a href="https://hr.economictimes.indiatimes.com/news/workplace-4-0/talent-management/responsibility-of-building-sustaining-a-great-work-culture-doesnt-lie-with-the-chro-alone-rohit-hasteer/78800394" target="_blank" rel="noopener">Economic Times HR World</a></p>\r\n<p><a href="https://allthingstalent.org/2020/10/27/people-function-paradox-navigators-in-startups/" target="_blank" rel="noopener">People Function: The Paradox Navigators in Startups | All Things Talent |</a></p>',
      createdDate: "2022-02-07T17:12:02",
      updatedDate: "2022-11-04T17:10:00",
      isPublished: "1",
      publishDate: "",
      position: "30",
      category: "",
      startdate: "",
      enddate: "",
    },
    {
      id: "160",
      Hrid: "160",
      KeyIndex: "160",
      fullName: "Ms. Jhilik Sharma",
      designation: "CHRO India and Global Learning",
      email: "",
      mobile: "",
      currentCompany: "Anthology Inc",
      location: "Bengaluru",
      totalExperience: "20 years",
      yrsCurrentOrg: "1+ years",
      shortDescription:
        "<p>An experienced executive with 20 plus years of experience in HR Strategy, Organisation Transformation &amp; Change Management, Jhilik&rsquo;s role at Anthology focuses on creating a great employee experience, internal readiness of employees &amp; creating a culture in line with the company&rsquo;s growth strategy. As head of Global Learning, her role involves creating an exceptional learning experience not just for employees but also for Anthology&rsquo;s customers and partners worldwide.<br /><br />Jhilik&rsquo;s role was pivotal in the transformation of the legacy company to Anthology as it is today. Ed-tech as an industry has grown in leaps and bounds very quickly and adapting to this change especially during the pandemic years has been critical. With her expertise, Jhilik brought to the forefront a focus on talent strategy that supports individual growth to attract talent. Thus, was born Anthology Academy &ndash; an erstwhile, client-exclusive learning center that was extended to support the learning and growth of all Anthologists. Jhilik&rsquo;s experience in the business and interactions with customers has given her the strength of looking at opportunities for business growth for the company and see her portfolio expand beyond the HR roles.<br /><br />She also runs the Adoption Services / Changes Management Services for Anthology for the International Markets, as a parallel activity to professional services in putting together roadmaps for product adoption and process acceptance during and post-implementation.<br /><br />In her earlier roles, she was part of Thomson Reuters India and UK leadership team, where she led the people agenda for Thomson Reuters Merger for South Asia and UK Sales. Prior to that she was Mergers &amp; Acquisitions Head, Thomson Reuters India. Here she successfully led the integration for Thomson Reuters India from 2008 &ndash; 2012. She focused on creating a vision and case for change, engaging key stakeholders, aligning the various change levers, leading communications strategies and plans &amp; overseeing the program management of 6000+ staff. She also led the Sales Transformation for Thomson Reuters London for 4000+ Sales staff across UK &amp; Asia. She has also worked on Talent Strategy Design: Aligning Talent Management models to suit organization's stage of growth. She strategized and led the execution of the Talent Management Plan during the Thomson Reuters Merger for over 6000 staff &ndash; including Talent risks assessment, building new Capabilities &amp; Competency Modelling<br /><br />When asked what she loves about her job, she said, &ldquo;There are so many aspects I love about my job&hellip;working with great colleagues across different locations like LATAM, U.S., U.K., Canada &amp; India. I get to understand different cultures, hear fun stories around the world, hear different thoughts &amp; ideas. My role is also unique as I have the privilege of interacting with all my staff as well as our customers globally, which enables me to look at ideas and solutions from both perspectives.&rdquo;</p>",
      areaOfExpertise:
        "<p>&bull; People strategy <br />&bull; Talent management<br />&bull; Change Management<br />&bull; Talent Strategy Design<br />&bull; Sales Transformation</p>",
      workHistory:
        "<p>2020 - Present <br />Chief Human Resources Officer India &amp; Global Learning <br />Anthology Inc <br /><br />2011 - 2020 <br />Vice President HR <br />Campus Management International and Talisma Corporation <br /><br />2008 - 2011 <br />Mergers and Acquisitions Head &ndash; Human Resources <br />Thomas Reuters <br /><br />2005 - 2008 <br />Associate Vice President HR <br />Reuters India <br /><br />2003 - 2005 <br />Specialist HR <br />Accenture India</p>",
      awardsAchievements:
        "<p>(i) Best Workplace Award &ndash; Talisma &ndash; 2013</p>\r\n<p>(ii) Award of Excellence from CEO &ndash; Leading successful Integration for India &ndash; 2009 (Thomson Reuters, India)</p>\r\n<p>(iii) Helen Keller Award &ndash; Diversity Hiring &ndash; 2008 (Thomson Reuters, India)</p>\r\n<p>(iv) Service Excellence Award &ndash; Business HR 2007 (Thomson Reuters, India)</p>\r\n<p>(v) Service Excellence Award &ndash; Recruitment 2005 (Accenture India)</p>",
      connectToLinkdin: "",
      connectToTwitter: "",
      website: "",
      profilePicture:
        "https://api.timesascent.com/media/HRprofessional/Ms. Jhilik Sharma/2022/01/10/1641820740.jpg",
      currentCompanyLogo: "",
      featuredMedia:
        '<p><a href="https://www.siliconindia.com/spotlight/company/talisma/jhilik-sharma-cid-234-eid-81.html" target="_blank" rel="noopener"> Jhilik Sharma</a></p>',
      createdDate: "2022-01-10T18:49:00",
      updatedDate: "2022-11-04T17:09:44",
      isPublished: "1",
      publishDate: "",
      position: "35",
      category: "",
      startdate: "",
      enddate: "",
    },
  ],
  message: "data found ",
};

export const forumdata = {
  status_code: 200,
  status: "Success",
  Questions: [
    {
      ID: 165,
      KeyIndex: 165,
      ForumQuestionID: "157f46ef-8eb6-11ed-8fdc-064df626ed42",
      Name: "Yash Shukla",
      Email: "yash@gmail.com",
      Question:
        "What can companies do to accommodate the needs and concerns of employees who prefer remote work?",
      AdminApproved: "Approved",
      IsDeleted: "0",
      CreatedAt: "2023-01-07T23:37:01",
      CreatedBy: "System",
      UpdatedAt: "2023-01-07T23:37:01",
      UpdatedBy: "System",
      answers: [
        {
          ID: 161,
          KeyIndex: 161,
          ForumAnswerID: "2ee9ae2f-8eb6-11ed-8fdc-064df626ed42",
          ForumQuestionID: "157f46ef-8eb6-11ed-8fdc-064df626ed42",
          Name: "Arnav Chauhan",
          Email: "arnav@gmail.com",
          Answer:
            "One option for companies to consider is offering a hybrid model where employees are able to work both from home and the office. This can allow employees to continue enjoying the benefits of remote work while still maintaining some level of in-office collaboration. Companies could also consider offering additional support for employees returning to the office, such as providing personal protective equipment and implementing safety measures to reduce the risk of contracting COVID-19. It may also be helpful for companies to communicate with their employees and listen to their concerns and preferences regarding remote work.",
          AdminApproved: "Approved",
          DefaultAnswer: "0",
          IsDeleted: "0",
          CreatedAt: "2023-01-07T23:37:44",
          CreatedBy: "System",
          UpdatedAt: "2023-01-07T23:37:44",
          UpdatedBy: "System",
        },
      ],
      answersCount: 1,
    },
    {
      ID: 164,
      KeyIndex: 164,
      ForumQuestionID: "db503e75-8eb5-11ed-8fdc-064df626ed42",
      Name: "Bhaskar Mishra",
      Email: "bhaskar@gmail.com",
      Question:
        "How do I, as a woman, talk to my family about shared responsibilities?",
      AdminApproved: "Approved",
      IsDeleted: "0",
      CreatedAt: "2023-01-07T23:35:23",
      CreatedBy: "System",
      UpdatedAt: "2023-01-07T23:35:23",
      UpdatedBy: "System",
      answers: [
        {
          ID: 160,
          KeyIndex: 160,
          ForumAnswerID: "f17c02b1-8eb5-11ed-8fdc-064df626ed42",
          ForumQuestionID: "db503e75-8eb5-11ed-8fdc-064df626ed42",
          Name: "Raghav Agrawal",
          Email: "raghav@gmail.com",
          Answer:
            "All members of society need to view economic and domestic concerns as non-gendered concerns. In a familial unit, both partners must equally share responsibilities. Talk to your partner and try to come up with a schedule that incorporates all your responsibilities. You must remember that communication is the key.",
          AdminApproved: "Approved",
          DefaultAnswer: "0",
          IsDeleted: "0",
          CreatedAt: "2023-01-07T23:36:00",
          CreatedBy: "System",
          UpdatedAt: "2023-01-07T23:36:00",
          UpdatedBy: "System",
        },
      ],
      answersCount: 1,
    },
    {
      ID: 163,
      KeyIndex: 163,
      ForumQuestionID: "a98ea61b-8eb5-11ed-8fdc-064df626ed42",
      Name: "Anuj Vishwakarma",
      Email: "anuj@gmail.com",
      Question: "Is the manufacturing sector volatile?",
      AdminApproved: "Approved",
      IsDeleted: "0",
      CreatedAt: "2023-01-07T23:34:00",
      CreatedBy: "System",
      UpdatedAt: "2023-01-07T23:34:00",
      UpdatedBy: "System",
      answers: [
        {
          ID: 159,
          KeyIndex: 159,
          ForumAnswerID: "c4f29834-8eb5-11ed-8fdc-064df626ed42",
          ForumQuestionID: "a98ea61b-8eb5-11ed-8fdc-064df626ed42",
          Name: "Shreyasireen Nayak",
          Email: "shreya@gmail.com",
          Answer:
            "It is important to note that the job market for manufacturing workers can be influenced by several factors, such as economic conditions, technological change, and shifts in consumer demand. It is always a good idea to stay informed about the current job market and to continuously update your skills and qualifications to increase your chances of finding employment in the manufacturing sector.",
          AdminApproved: "Approved",
          DefaultAnswer: "0",
          IsDeleted: "0",
          CreatedAt: "2023-01-07T23:34:46",
          CreatedBy: "System",
          UpdatedAt: "2023-01-07T23:34:46",
          UpdatedBy: "System",
        },
      ],
      answersCount: 1,
    },
    {
      ID: 162,
      KeyIndex: 162,
      ForumQuestionID: "df12bbd3-8d26-11ed-8fdc-064df626ed42",
      Name: "Japneet Arora",
      Email: "jap@gmail.com",
      Question: 'What is the "she-cession"?',
      AdminApproved: "Approved",
      IsDeleted: "0",
      CreatedAt: "2023-01-05T23:59:20",
      CreatedBy: "System",
      UpdatedAt: "2023-01-05T23:59:20",
      UpdatedBy: "System",
      answers: [
        {
          ID: 158,
          KeyIndex: 158,
          ForumAnswerID: "fd26e040-8d26-11ed-8fdc-064df626ed42",
          ForumQuestionID: "df12bbd3-8d26-11ed-8fdc-064df626ed42",
          Name: "Arnav Chauhan",
          Email: "arnav@gmail.com",
          Answer:
            'The "she-cession" refers to the disproportionate impact that the COVID-19 pandemic has had on women and the economic burden that they have had to bear as a result. Women have been more likely to work in industries that have been hardest hit by the crisis, and they have also faced higher rates of job loss and economic insecurity. The "she-cession" has also disproportionately affected women of color, who have faced higher rates of job loss and economic insecurity.',
          AdminApproved: "Approved",
          DefaultAnswer: "0",
          IsDeleted: "0",
          CreatedAt: "2023-01-06T00:00:11",
          CreatedBy: "System",
          UpdatedAt: "2023-01-06T00:00:11",
          UpdatedBy: "System",
        },
      ],
      answersCount: 1,
    },
    {
      ID: 161,
      KeyIndex: 161,
      ForumQuestionID: "9c61590d-8d26-11ed-8fdc-064df626ed42",
      Name: "Pratiti Srivastava",
      Email: "pratiti@gmail.com",
      Question: "Is it difficult to find jobs in the service sector?",
      AdminApproved: "Approved",
      IsDeleted: "0",
      CreatedAt: "2023-01-05T23:57:28",
      CreatedBy: "System",
      UpdatedAt: "2023-01-05T23:57:28",
      UpdatedBy: "System",
      answers: [
        {
          ID: 157,
          KeyIndex: 157,
          ForumAnswerID: "bc61f7e0-8d26-11ed-8fdc-064df626ed42",
          ForumQuestionID: "9c61590d-8d26-11ed-8fdc-064df626ed42",
          Name: "Shreyasireen Nayak",
          Email: "shreya@gmail.com",
          Answer:
            "It is generally not difficult to find jobs in the service sector, as it is a large and diverse industry that includes a wide range of industries and occupations. However, the availability of specific jobs in the service sector can vary depending on several factors, including the local job market, the specific industry and occupation, and an individual's qualifications and experience. Some service sector industries, such as healthcare and education, may have a higher demand for workers, while other industries may have more competitive job markets.",
          AdminApproved: "Approved",
          DefaultAnswer: "0",
          IsDeleted: "0",
          CreatedAt: "2023-01-05T23:58:22",
          CreatedBy: "System",
          UpdatedAt: "2023-01-05T23:58:22",
          UpdatedBy: "System",
        },
      ],
      answersCount: 1,
    },
    {
      ID: 160,
      KeyIndex: 160,
      ForumQuestionID: "5e3d5b7c-8d26-11ed-8fdc-064df626ed42",
      Name: "Aman Verma",
      Email: "aman@gmail.com",
      Question:
        "I have a small firm and cannot spend on an on-site childcare facility. What to do?",
      AdminApproved: "Approved",
      IsDeleted: "0",
      CreatedAt: "2023-01-05T23:55:44",
      CreatedBy: "System",
      UpdatedAt: "2023-01-05T23:55:44",
      UpdatedBy: "System",
      answers: [
        {
          ID: 156,
          KeyIndex: 156,
          ForumAnswerID: "7a2c11d7-8d26-11ed-8fdc-064df626ed42",
          ForumQuestionID: "5e3d5b7c-8d26-11ed-8fdc-064df626ed42",
          Name: "Raghav Agrawal",
          Email: "raghav@gmail.com",
          Answer:
            "All the businesses in the locality, through a common business representation body (vyapar sangh in India), can create a proper childcare facility with a pooling of resources and govern by trust or cooperative.",
          AdminApproved: "Approved",
          DefaultAnswer: "0",
          IsDeleted: "0",
          CreatedAt: "2023-01-05T23:56:31",
          CreatedBy: "System",
          UpdatedAt: "2023-01-05T23:56:31",
          UpdatedBy: "System",
        },
      ],
      answersCount: 1,
    },
    {
      ID: 159,
      KeyIndex: 159,
      ForumQuestionID: "8935b5ed-8c5d-11ed-8fdc-064df626ed42",
      Name: "Anoop Kundra",
      Email: "ANOOP@GMAIL.COM",
      Question: "How do senior executives contribute to a company's success?",
      AdminApproved: "Approved",
      IsDeleted: "0",
      CreatedAt: "2023-01-04T23:58:08",
      CreatedBy: "System",
      UpdatedAt: "2023-01-04T23:58:08",
      UpdatedBy: "System",
      answers: [
        {
          ID: 155,
          KeyIndex: 155,
          ForumAnswerID: "11dd72d2-8c61-11ed-8fdc-064df626ed42",
          ForumQuestionID: "8935b5ed-8c5d-11ed-8fdc-064df626ed42",
          Name: "Arnav Chauhan",
          Email: "arnav@gmail.com",
          Answer:
            "Senior executives contribute to a company's success through their leadership skills, expertise in digital transformation, and ability to build and maintain relationships. Their insights and guidance are invaluable as companies navigate the rapidly changing business landscape, and their experience and expertise can help to ensure that companies are well-positioned to succeed in the digital age.",
          AdminApproved: "Approved",
          DefaultAnswer: "0",
          IsDeleted: "0",
          CreatedAt: "2023-01-05T00:23:25",
          CreatedBy: "System",
          UpdatedAt: "2023-01-05T00:23:25",
          UpdatedBy: "System",
        },
      ],
      answersCount: 1,
    },
    {
      ID: 158,
      KeyIndex: 158,
      ForumQuestionID: "390dc3cd-8c5d-11ed-8fdc-064df626ed42",
      Name: "Prateek Kumar",
      Email: "prateek@gmail.com",
      Question: "What impact will working from home have on productivity?",
      AdminApproved: "Approved",
      IsDeleted: "0",
      CreatedAt: "2023-01-04T23:55:53",
      CreatedBy: "System",
      UpdatedAt: "2023-01-04T23:55:53",
      UpdatedBy: "System",
      answers: [
        {
          ID: 153,
          KeyIndex: 153,
          ForumAnswerID: "5439b3ec-8c5d-11ed-8fdc-064df626ed42",
          ForumQuestionID: "390dc3cd-8c5d-11ed-8fdc-064df626ed42",
          Name: "Shreyasireen Nayak",
          Email: "shreya@gmail.com",
          Answer:
            "Productivity does not need to decrease at all. Due to the absence of commutes and office distractions, it can be kept up, if not improved. Naturally, if you are at home with your partner or children, those problems will need to be resolved. Your capacity to settle issues swiftly when you cannot meet in real-time or in person could be another issue. That could lead to delays. However, aside from that, I do not anticipate a decline in production. Strong evidence supports the idea that nothing needs to change.",
          AdminApproved: "Approved",
          DefaultAnswer: "0",
          IsDeleted: "0",
          CreatedAt: "2023-01-04T23:56:39",
          CreatedBy: "System",
          UpdatedAt: "2023-01-04T23:56:39",
          UpdatedBy: "System",
        },
      ],
      answersCount: 1,
    },
    {
      ID: 157,
      KeyIndex: 157,
      ForumQuestionID: "ee6ebfb7-8c5c-11ed-8fdc-064df626ed42",
      Name: "Meesum Rizvi",
      Email: "meesam@gmail.com",
      Question:
        "Our company does not provide childcare benefits, and I have to work with my spouse to have a decent income for living. What to do?",
      AdminApproved: "Approved",
      IsDeleted: "0",
      CreatedAt: "2023-01-04T23:53:48",
      CreatedBy: "System",
      UpdatedAt: "2023-01-04T23:53:48",
      UpdatedBy: "System",
      answers: [
        {
          ID: 152,
          KeyIndex: 152,
          ForumAnswerID: "1023e9fe-8c5d-11ed-8fdc-064df626ed42",
          ForumQuestionID: "ee6ebfb7-8c5c-11ed-8fdc-064df626ed42",
          Name: "Raghav Agarwal",
          Email: "raghav@gmail.com",
          Answer:
            "There are many working parents in your area facing a similar situation. A pooling system can be created among you where a typical childcare facility can be home to anyone on a rotational basis with the nanny, and one trustable member of anyone’s family can take care.",
          AdminApproved: "Approved",
          DefaultAnswer: "0",
          IsDeleted: "0",
          CreatedAt: "2023-01-04T23:54:44",
          CreatedBy: "System",
          UpdatedAt: "2023-01-04T23:54:44",
          UpdatedBy: "System",
        },
      ],
      answersCount: 1,
    },
    {
      ID: 156,
      KeyIndex: 156,
      ForumQuestionID: "b5646153-8b91-11ed-8fdc-064df626ed42",
      Name: "Anupam Vijay",
      Email: "anuvi@gmail.com",
      Question:
        "How can companies address conflicts between in-office and remote workers?",
      AdminApproved: "Approved",
      IsDeleted: "0",
      CreatedAt: "2023-01-03T23:39:04",
      CreatedBy: "System",
      UpdatedAt: "2023-01-03T23:39:04",
      UpdatedBy: "System",
      answers: [
        {
          ID: 151,
          KeyIndex: 151,
          ForumAnswerID: "e3ba8e28-8b91-11ed-8fdc-064df626ed42",
          ForumQuestionID: "b5646153-8b91-11ed-8fdc-064df626ed42",
          Name: "Arnav Chauhan",
          Email: "arnav@gmail.com",
          Answer:
            "To address conflicts between in-office and remote workers, companies can establish clear policies and guidelines for communication and collaboration, provide training and resources to help employees communicate and collaborate effectively, and address any perceived inequities between in-office and remote workers. It is also important for companies to foster a culture of inclusivity and respect for all employees, regardless of whether they are working in the office or remotely.",
          AdminApproved: "Approved",
          DefaultAnswer: "0",
          IsDeleted: "0",
          CreatedAt: "2023-01-03T23:40:22",
          CreatedBy: "System",
          UpdatedAt: "2023-01-03T23:40:22",
          UpdatedBy: "System",
        },
      ],
      answersCount: 1,
    },
  ],
  TotalCount: 130,
  message: "Data found",
};
